# Project Metadata
sonar.projectKey=mystic-framework.version
sonar.organization=mystic-framework
sonar.projectName=version
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Source Structure
sonar.sources=source
sonar.tests=test

# Enable Modules Support
sonar.cfamily.enableModules=true
