name: "Coverage"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: SonarQube Coverage
        uses: mystic-framework/github-actions/sonarqube@v1
        with:
          language: cpp
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          cpp-coverage-tool: llvm-cov
          cpp-coverage-option: MYSTICVERSION_ENABLE_COVERAGE
